from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

# PUBLIC_INTERFACE
class User(db.Model):
    """User model for authentication and personal info."""
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    oauth_sub = db.Column(db.String(255), unique=True, nullable=False) # subject from Google
    email = db.Column(db.String(120), unique=True, nullable=False)
    name = db.Column(db.String(120))
    profile_pic = db.Column(db.String(300))
    preferences = db.relationship('UserPreference', backref='user', uselist=False)
    bookmarks = db.relationship('Bookmark', backref='user', lazy='dynamic')
    registered_at = db.Column(db.DateTime, default=datetime.utcnow)

# PUBLIC_INTERFACE
class UserPreference(db.Model):
    """Model for storing user preferences."""
    __tablename__ = "user_preferences"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    reading_level = db.Column(db.String(50))
    summary_detail = db.Column(db.String(50))
    preferred_topics = db.Column(db.String(255))  # Comma-separated topic list

# PUBLIC_INTERFACE
class Summary(db.Model):
    """Article Summaries generated by the AI."""
    __tablename__ = "summaries"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    source_type = db.Column(db.String(20)) # 'url', 'text', 'news'
    source_value = db.Column(db.Text) # url or raw text
    summary_text = db.Column(db.Text)
    input_title = db.Column(db.String(300))
    summary_json = db.Column(db.Text) # optional, for richer summaries
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

# PUBLIC_INTERFACE
class Bookmark(db.Model):
    """User bookmarks for saving favorite summaries."""
    __tablename__ = "bookmarks"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    summary_id = db.Column(db.Integer, db.ForeignKey('summaries.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    summary = db.relationship('Summary', backref='bookmarked')

